### ISSUE TITLE
undefined method app_token= for TestFlightConfig

### ISSUE THREAD

**Issue by andyjeffries** [HipByte/motion-testflight#17]
I'm using 1.4 of motion-testflight, verified with:

```
  $ grep motion-testflight Gemfile.lock
    motion-testflight (1.4)
    motion-testflight
```

I'm using 1.2.4 of the SDK (as verified by looking at my testflightapp.com dashboard for the build)..  In my Rakefile I have:

``` ruby
  app.testflight do
    app.testflight.sdk         = 'vendor/TestFlight'
    app.testflight.api_token   = '{my-api-token}'
    app.testflight.team_token  = '{my-team-token}'
    app.testflight.app_token   = '{my-app-token}'
    app.testflight.notify      = true
  end
```

(obviously removing the actual tokens used).  When I try to "rake testflight" I get:

```
$ rake testflight notes="Testing api_token in testflight_launcher"
rake aborted!
undefined method `app_token=' for #<TestFlightConfig:0x007f9d52024580>
/Users/andy/Code/Rakefile:34:in `block (2 levels) in <top (required)>'
/Users/andy/.rvm/gems/ruby-1.9.3-p194/gems/motion-testflight-1.4/lib/motion/project/testflight.rb:85:in `testflight'
/Users/andy/Code/Rakefile:30:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:111:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:111:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:111:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:111:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:60:in `config'
/Users/andy/.rvm/gems/ruby-1.9.3-p194/gems/motion-testflight-1.4/lib/motion/project/testflight.rb:102:in `block (2 levels) in <top (required)>'
Tasks: TOP => testflight => testflight:submit
(See full trace by running task with --trace)
```

Your homepage says:

"If you’re using Testflight 1.2 or above, you should also add the app_token."

```
# ...
app.testflight do
  # ...

  app.testflight.app_token = '<insert your APP token here>'
end
```

What am I doing wrong?

**Comment by Watson1978** [comment]
The `app_token=` method that will be contained in next release (version 1.5)
So, when you would like to use it as soon as possible, you could use it via [bundler](https://rubygems.org/gems/bundler) gem.
